import '../config/app_config.dart';
import '../models/menu_item.dart';
import '../models/restaurant.dart';
import '../models/starter_menu.dart';
import 'menu_repository.dart';

/// Supabase 미연결 시 사용하는 로컬 mock 데이터.
/// 등록 메뉴(가게 포함) + 스타터 메뉴를 제공합니다.
class MockDataRepository implements MenuRepository {
  static final List<Restaurant> _restaurants = [
    Restaurant(
      id: 'r1',
      name: '주먹식당',
      address: '서울 강남구 강남대로 396',
      phone: '02-1234-5678',
      lat: 37.4985,
      lng: 127.0272,
      category: '한식',
      source: 'admin_seed',
      isTakeoutAvailable: true,
    ),
    Restaurant(
      id: 'r2',
      name: '혼밥왕국',
      address: '서울 강남구 테헤란로 151',
      phone: '02-2345-6789',
      lat: 37.4992,
      lng: 127.0284,
      category: '한식',
      source: 'admin_seed',
      isDeliveryAvailable: true,
    ),
    Restaurant(
      id: 'r3',
      name: '면식당',
      address: '서울 강남구 역삼로 160',
      phone: '02-3456-7890',
      lat: 37.4968,
      lng: 127.0299,
      category: '일식',
      source: 'admin_seed',
      isTakeoutAvailable: true,
      isDeliveryAvailable: true,
    ),
  ];

  static final Map<String, Restaurant> _rMap = {
    for (final r in _restaurants) r.id: r,
  };

  static final List<MenuItem> _menus = [
    MenuItem(
      id: 'm1',
      restaurantId: 'r1',
      name: '김치제육덮밥',
      description: '매콤한 제육볶음과 신선한 김치가 어우러진 한 그릇 밥',
      price: 9500,
      category: '한식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      spicyLevel: 3,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm2',
      restaurantId: 'r1',
      name: '된장찌개 정식',
      description: '깊은 맛의 된장찌개와 밥, 반찬 3가지',
      price: 8000,
      category: '한식',
      isSoloFriendly: true,
      spicyLevel: 1,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm3',
      restaurantId: 'r1',
      name: '비빔밥 (채식)',
      description: '고추장 대신 간장 양념, 비건 가능',
      price: 8500,
      category: '한식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      isVeganOption: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm4',
      restaurantId: 'r2',
      name: '순대국밥',
      description: '진한 육수의 순대국밥, 1인 세트',
      price: 7500,
      category: '한식',
      isDeliveryAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm5',
      restaurantId: 'r2',
      name: '참치마요덮밥',
      description: '참치와 마요네즈의 조화',
      price: 7000,
      category: '한식',
      isDeliveryAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm6',
      restaurantId: 'r3',
      name: '돈카츠',
      description: '바삭한 등심 돈카츠',
      price: 11000,
      category: '일식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm7',
      restaurantId: 'r3',
      name: '냉모밀',
      description: '시원한 메밀 소바',
      price: 9000,
      category: '일식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      isVeganOption: true,
      source: 'admin_seed',
    ),
  ];

  static final List<StarterMenu> _starters = [
    const StarterMenu(
      id: 's1',
      name: '김치제육덮밥',
      description: '매콤한 제육볶음과 김치',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '김치제육덮밥',
    ),
    const StarterMenu(
      id: 's2',
      name: '된장찌개 정식',
      description: '구수한 된장찌개 정식',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '된장찌개',
    ),
    const StarterMenu(
      id: 's3',
      name: '비빔밥',
      description: '나물과 고추장의 조화',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '비빔밥',
    ),
    const StarterMenu(
      id: 's4',
      name: '순두부찌개',
      description: '얼큰한 순두부찌개',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '순두부찌개',
    ),
    const StarterMenu(
      id: 's5',
      name: '국밥',
      description: '뜨끈한 국밥 한 그릇',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '국밥',
    ),
    const StarterMenu(
      id: 's6',
      name: '짜장면',
      description: '진한 춘장 소스',
      category: '중식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '짜장면',
    ),
    const StarterMenu(
      id: 's7',
      name: '마라탕',
      description: '얼얼한 마라 향신료',
      category: '중식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '마라탕',
    ),
    const StarterMenu(
      id: 's8',
      name: '짬뽕',
      description: '얼큰한 해물 국물',
      category: '중식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '짬뽕',
    ),
    const StarterMenu(
      id: 's9',
      name: '초밥',
      description: '신선한 한 입 초밥',
      category: '일식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 20000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '초밥',
    ),
    const StarterMenu(
      id: 's10',
      name: '돈카츠',
      description: '바삭한 돈카츠',
      category: '일식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '돈카츠',
    ),
    const StarterMenu(
      id: 's11',
      name: '냉모밀',
      description: '시원한 소바',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '냉모밀',
    ),
    const StarterMenu(
      id: 's12',
      name: '우동',
      description: '뜨끈한 우동',
      category: '일식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '우동',
    ),
    const StarterMenu(
      id: 's13',
      name: '알리오올리오',
      description: '마늘 올리브오일 파스타',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '알리오올리오',
    ),
    const StarterMenu(
      id: 's14',
      name: '토마토파스타',
      description: '신선한 토마토 소스',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '토마토파스타',
    ),
    const StarterMenu(
      id: 's15',
      name: '샐러드볼',
      description: '채소와 단백질의 건강 한 그릇',
      category: '양식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '샐러드볼',
    ),
    const StarterMenu(
      id: 's16',
      name: '떡볶이',
      description: '매콤한 떡볶이',
      category: '분식',
      expectedMinPrice: 4000,
      expectedMaxPrice: 8000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '떡볶이',
    ),
    const StarterMenu(
      id: 's17',
      name: '김밥',
      description: '한국식 롤',
      category: '분식',
      expectedMinPrice: 3000,
      expectedMaxPrice: 6000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '김밥',
    ),
    const StarterMenu(
      id: 's18',
      name: '라볶이',
      description: '라면+떡볶이 조합',
      category: '분식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '라볶이',
    ),
    const StarterMenu(
      id: 's19',
      name: '햄버거세트',
      description: '버거+감자튀김 세트',
      category: '햄버거',
      expectedMinPrice: 7000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '햄버거',
    ),
    const StarterMenu(
      id: 's20',
      name: '치킨버거',
      description: '바삭한 치킨 버거',
      category: '햄버거',
      expectedMinPrice: 6000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치킨버거',
    ),
    const StarterMenu(
      id: 's21',
      name: '쌀국수',
      description: '베트남식 쌀국수',
      category: '면',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      // 지도 검색어에 불필요한 단어가 붙지 않도록 음식명만 사용 (기존 '쌀국수 포'가
      // 지도 검색 시 "내 주변 쌀국수 포"로 표시되던 문제의 원인이었음).
      searchKeyword: '쌀국수',
    ),
    const StarterMenu(
      id: 's22',
      name: '아보카도 토스트',
      description: '건강 브런치',
      category: '카페',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '아보카도토스트',
    ),
    // s23~s50 추가
    const StarterMenu(
      id: 's23',
      name: '김치찌개',
      description: '진한 김치 국물에 돼지고기와 두부',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '김치찌개',
    ),
    const StarterMenu(
      id: 's24',
      name: '순댓국',
      description: '구수한 순대국 한 그릇',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '순댓국',
    ),
    const StarterMenu(
      id: 's25',
      name: '설렁탕',
      description: '오래 끓인 맑은 사골 육수',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      searchKeyword: '설렁탕',
    ),
    const StarterMenu(
      id: 's26',
      name: '갈비탕',
      description: '진한 소갈비 국물',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      searchKeyword: '갈비탕',
    ),
    const StarterMenu(
      id: 's27',
      name: '부대찌개',
      description: '햄·소시지·라면이 들어간 얼큰 찌개',
      category: '한식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '부대찌개',
    ),
    const StarterMenu(
      id: 's28',
      name: '제육볶음',
      description: '매콤달콤한 돼지고기 볶음',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '제육볶음',
    ),
    const StarterMenu(
      id: 's29',
      name: '불고기',
      description: '달콤한 간장 양념 소불고기',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '불고기',
    ),
    const StarterMenu(
      id: 's30',
      name: '삼겹살',
      description: '두툼한 삼겹살 구이',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 20000,
      searchKeyword: '삼겹살',
    ),
    const StarterMenu(
      id: 's31',
      name: '닭갈비',
      description: '매콤한 춘천식 닭갈비',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '닭갈비',
    ),
    const StarterMenu(
      id: 's32',
      name: '찜닭',
      description: '달콤짭짤한 안동식 찜닭',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 18000,
      isDeliveryFriendly: true,
      searchKeyword: '찜닭',
    ),
    const StarterMenu(
      id: 's33',
      name: '닭강정',
      description: '바삭하고 달콤한 닭강정',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '닭강정',
    ),
    const StarterMenu(
      id: 's34',
      name: '치킨',
      description: '바삭한 프라이드 치킨',
      category: '치킨',
      expectedMinPrice: 10000,
      expectedMaxPrice: 20000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치킨',
    ),
    const StarterMenu(
      id: 's35',
      name: '족발',
      description: '쫄깃한 족발 보쌈 세트',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 25000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '족발',
    ),
    const StarterMenu(
      id: 's36',
      name: '보쌈',
      description: '수육과 김치를 함께 즐기는 보쌈',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 22000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '보쌈',
    ),
    const StarterMenu(
      id: 's37',
      name: '곱창볶음',
      description: '매콤하게 볶은 소곱창',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isSoloFriendly: true,
      searchKeyword: '곱창',
    ),
    const StarterMenu(
      id: 's38',
      name: '감자탕',
      description: '칼칼한 돼지 등뼈 감자탕',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '감자탕',
    ),
    const StarterMenu(
      id: 's39',
      name: '라면',
      description: '얼큰하고 뜨끈한 라면 한 그릇',
      category: '분식',
      expectedMinPrice: 4000,
      expectedMaxPrice: 7000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '라면',
    ),
    const StarterMenu(
      id: 's40',
      name: '순대볶음',
      description: '야채와 함께 볶은 매콤한 순대',
      category: '분식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '순대',
    ),
    const StarterMenu(
      id: 's41',
      name: '오므라이스',
      description: '계란 오믈렛에 케첩 볶음밥',
      category: '양식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '오므라이스',
    ),
    const StarterMenu(
      id: 's42',
      name: '라멘',
      description: '진한 국물의 일본식 라멘',
      category: '일식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      searchKeyword: '라멘',
    ),
    const StarterMenu(
      id: 's43',
      name: '규동',
      description: '달콤한 소고기 덮밥',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '규동',
    ),
    const StarterMenu(
      id: 's44',
      name: '탕수육',
      description: '바삭한 탕수육과 새콤달콤한 소스',
      category: '중식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 18000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '탕수육',
    ),
    const StarterMenu(
      id: 's45',
      name: '볶음밥',
      description: '고소한 계란 볶음밥',
      category: '중식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '볶음밥',
    ),
    const StarterMenu(
      id: 's46',
      name: '피자',
      description: '쫄깃한 도우의 화덕 피자',
      category: '피자',
      expectedMinPrice: 10000,
      expectedMaxPrice: 20000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '피자',
    ),
    const StarterMenu(
      id: 's47',
      name: '샌드위치',
      description: '신선한 재료의 수제 샌드위치',
      category: '카페',
      expectedMinPrice: 6000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '샌드위치',
    ),
    const StarterMenu(
      id: 's48',
      name: '스테이크',
      description: '부드러운 등심 스테이크',
      category: '양식',
      expectedMinPrice: 18000,
      expectedMaxPrice: 35000,
      isSoloFriendly: true,
      searchKeyword: '스테이크',
    ),
    const StarterMenu(
      id: 's49',
      name: '팟타이',
      description: '태국식 볶음 쌀국수',
      category: '면',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '팟타이',
    ),
    const StarterMenu(
      id: 's50',
      name: '카레라이스',
      description: '진한 일본식 카레와 밥',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '카레',
    ),
    // ── 2026-07 확장분: 약 50개 → 약 200개 (한쪽 카테고리 쏠림 방지,
    // 국내 사용자가 실제로 자주 찾는 음식 위주로 구성) ──────────────
    // 한식
    const StarterMenu(
      id: 's51',
      name: '계란말이',
      description: '폭신한 계란말이',
      category: '한식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '계란말이',
    ),
    const StarterMenu(
      id: 's52',
      name: '잡채',
      description: '당면과 채소볶음',
      category: '한식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '잡채',
    ),
    const StarterMenu(
      id: 's53',
      name: '육회',
      description: '신선한 소고기 육회',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '육회',
    ),
    const StarterMenu(
      id: 's54',
      name: '닭볶음탕',
      description: '매콤한 감자 닭볶음탕',
      category: '한식',
      expectedMinPrice: 18000,
      expectedMaxPrice: 25000,
      isDeliveryFriendly: true,
      searchKeyword: '닭볶음탕',
    ),
    const StarterMenu(
      id: 's55',
      name: '간장게장',
      description: '밥도둑 간장게장',
      category: '한식',
      expectedMinPrice: 20000,
      expectedMaxPrice: 30000,
      searchKeyword: '간장게장',
    ),
    const StarterMenu(
      id: 's56',
      name: '코다리조림',
      description: '매콤한 코다리조림',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 16000,
      isDeliveryFriendly: true,
      searchKeyword: '코다리조림',
    ),
    const StarterMenu(
      id: 's57',
      name: '오징어볶음',
      description: '매콤 쫄깃한 오징어볶음',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '오징어볶음',
    ),
    const StarterMenu(
      id: 's58',
      name: '생선구이',
      description: '고소한 생선구이 정식',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      searchKeyword: '생선구이',
    ),
    const StarterMenu(
      id: 's59',
      name: '갈치조림',
      description: '칼칼한 갈치조림',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 20000,
      searchKeyword: '갈치조림',
    ),
    const StarterMenu(
      id: 's60',
      name: '낙지볶음',
      description: '매콤한 낙지볶음',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isDeliveryFriendly: true,
      searchKeyword: '낙지볶음',
    ),
    const StarterMenu(
      id: 's61',
      name: '청국장',
      description: '구수한 청국장 정식',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '청국장',
    ),
    const StarterMenu(
      id: 's62',
      name: '소고기뭇국',
      description: '깊은 맛의 소고기뭇국',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      searchKeyword: '소고기뭇국',
    ),
    const StarterMenu(
      id: 's63',
      name: '닭한마리',
      description: '진한 육수의 닭한마리',
      category: '한식',
      expectedMinPrice: 25000,
      expectedMaxPrice: 32000,
      searchKeyword: '닭한마리',
    ),
    const StarterMenu(
      id: 's64',
      name: '두부김치',
      description: '얼큰 김치와 부드러운 두부',
      category: '한식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      searchKeyword: '두부김치',
    ),
    const StarterMenu(
      id: 's65',
      name: '어묵탕',
      description: '따끈한 어묵탕',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 20000,
      searchKeyword: '어묵탕',
    ),
    const StarterMenu(
      id: 's66',
      name: '감자전',
      description: '고소한 감자전',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '감자전',
    ),
    const StarterMenu(
      id: 's67',
      name: '파전',
      description: '바삭한 해물파전',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 16000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '파전',
    ),
    const StarterMenu(
      id: 's68',
      name: '도토리묵무침',
      description: '새콤달콤 도토리묵무침',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isVeganOption: true,
      searchKeyword: '도토리묵',
    ),
    const StarterMenu(
      id: 's69',
      name: '아귀찜',
      description: '매콤한 아귀찜',
      category: '한식',
      expectedMinPrice: 20000,
      expectedMaxPrice: 28000,
      searchKeyword: '아귀찜',
    ),
    const StarterMenu(
      id: 's70',
      name: '홍어삼합',
      description: '삭힌 홍어와 삼겹살, 김치',
      category: '한식',
      expectedMinPrice: 25000,
      expectedMaxPrice: 35000,
      searchKeyword: '홍어삼합',
    ),
    const StarterMenu(
      id: 's71',
      name: '육전',
      description: '담백한 소고기 육전',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 20000,
      searchKeyword: '육전',
    ),
    const StarterMenu(
      id: 's72',
      name: '떡갈비',
      description: '달콤짭짤한 떡갈비',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '떡갈비',
    ),
    // 면
    const StarterMenu(
      id: 's73',
      name: '칼국수',
      description: '진한 멸치육수 칼국수',
      category: '면',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '칼국수',
    ),
    const StarterMenu(
      id: 's74',
      name: '수제비',
      description: '쫄깃한 수제비',
      category: '면',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '수제비',
    ),
    const StarterMenu(
      id: 's75',
      name: '잔치국수',
      description: '따뜻한 멸치 잔치국수',
      category: '면',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      searchKeyword: '잔치국수',
    ),
    const StarterMenu(
      id: 's76',
      name: '비빔국수',
      description: '새콤매콤 비빔국수',
      category: '면',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '비빔국수',
    ),
    const StarterMenu(
      id: 's77',
      name: '열무국수',
      description: '시원한 열무 냉국수',
      category: '면',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isVeganOption: true,
      searchKeyword: '열무국수',
    ),
    const StarterMenu(
      id: 's78',
      name: '콩국수',
      description: '고소한 콩국수',
      category: '면',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isVeganOption: true,
      searchKeyword: '콩국수',
    ),
    const StarterMenu(
      id: 's79',
      name: '막국수',
      description: '메밀 향 가득한 막국수',
      category: '면',
      expectedMinPrice: 9000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      searchKeyword: '막국수',
    ),
    const StarterMenu(
      id: 's80',
      name: '소바',
      description: '시원한 일본식 소바',
      category: '면',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      searchKeyword: '소바',
    ),
    const StarterMenu(
      id: 's81',
      name: '탄탄면',
      description: '얼큰한 중국식 탄탄면',
      category: '면',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '탄탄면',
    ),
    const StarterMenu(
      id: 's82',
      name: '볶음우동',
      description: '불향 가득한 볶음우동',
      category: '면',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '볶음우동',
    ),
    const StarterMenu(
      id: 's83',
      name: '나가사키짬뽕',
      description: '뽀얀 국물의 나가사키짬뽕',
      category: '면',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '나가사키짬뽕',
    ),
    const StarterMenu(
      id: 's84',
      name: '회냉면',
      description: '새콤달콤 회냉면',
      category: '면',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      searchKeyword: '회냉면',
    ),
    // 밥
    const StarterMenu(
      id: 's85',
      name: '새우볶음밥',
      description: '탱글한 새우 볶음밥',
      category: '밥',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '새우볶음밥',
    ),
    const StarterMenu(
      id: 's86',
      name: '김치볶음밥',
      description: '고소한 김치볶음밥',
      category: '밥',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '김치볶음밥',
    ),
    const StarterMenu(
      id: 's87',
      name: '회덮밥',
      description: '신선한 회와 채소 비빔',
      category: '밥',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      searchKeyword: '회덮밥',
    ),
    const StarterMenu(
      id: 's88',
      name: '장어덮밥',
      description: '고소한 장어덮밥',
      category: '밥',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      isSoloFriendly: true,
      searchKeyword: '장어덮밥',
    ),
    const StarterMenu(
      id: 's89',
      name: '스테이크덮밥',
      description: '육즙 가득 스테이크덮밥',
      category: '밥',
      expectedMinPrice: 13000,
      expectedMaxPrice: 19000,
      isSoloFriendly: true,
      searchKeyword: '스테이크덮밥',
    ),
    const StarterMenu(
      id: 's90',
      name: '가츠동',
      description: '바삭한 돈카츠 덮밥',
      category: '밥',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '가츠동',
    ),
    const StarterMenu(
      id: 's91',
      name: '텐동',
      description: '바삭한 튀김 덮밥',
      category: '밥',
      expectedMinPrice: 10000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      searchKeyword: '텐동',
    ),
    const StarterMenu(
      id: 's92',
      name: '연어덮밥',
      description: '신선한 연어 덮밥',
      category: '밥',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      searchKeyword: '연어덮밥',
    ),
    const StarterMenu(
      id: 's93',
      name: '낙지덮밥',
      description: '매콤한 낙지 덮밥',
      category: '밥',
      expectedMinPrice: 10000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '낙지덮밥',
    ),
    const StarterMenu(
      id: 's94',
      name: '포케',
      description: '건강한 하와이안 포케',
      category: '밥',
      expectedMinPrice: 11000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '포케',
    ),
    // 국·탕·찌개
    const StarterMenu(
      id: 's95',
      name: '동태찌개',
      description: '얼큰한 동태찌개',
      category: '국·탕·찌개',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      searchKeyword: '동태찌개',
    ),
    const StarterMenu(
      id: 's96',
      name: '곰탕',
      description: '깊고 진한 곰탕',
      category: '국·탕·찌개',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '곰탕',
    ),
    const StarterMenu(
      id: 's97',
      name: '육개장',
      description: '얼큰한 육개장',
      category: '국·탕·찌개',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '육개장',
    ),
    const StarterMenu(
      id: 's98',
      name: '매운탕',
      description: '얼큰한 생선 매운탕',
      category: '국·탕·찌개',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '매운탕',
    ),
    const StarterMenu(
      id: 's99',
      name: '알탕',
      description: '얼큰한 알탕',
      category: '국·탕·찌개',
      expectedMinPrice: 14000,
      expectedMaxPrice: 20000,
      searchKeyword: '알탕',
    ),
    const StarterMenu(
      id: 's100',
      name: '뼈해장국',
      description: '진한 뼈해장국',
      category: '국·탕·찌개',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '뼈해장국',
    ),
    const StarterMenu(
      id: 's101',
      name: '콩나물국밥',
      description: '얼큰 시원한 콩나물국밥',
      category: '국·탕·찌개',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '콩나물국밥',
    ),
    const StarterMenu(
      id: 's102',
      name: '대구탕',
      description: '시원한 대구탕',
      category: '국·탕·찌개',
      expectedMinPrice: 13000,
      expectedMaxPrice: 19000,
      isSoloFriendly: true,
      searchKeyword: '대구탕',
    ),
    // 중식
    const StarterMenu(
      id: 's103',
      name: '마파두부',
      description: '얼큰한 마파두부',
      category: '중식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '마파두부',
    ),
    const StarterMenu(
      id: 's104',
      name: '유산슬',
      description: '고급스러운 유산슬',
      category: '중식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      isDeliveryFriendly: true,
      searchKeyword: '유산슬',
    ),
    const StarterMenu(
      id: 's105',
      name: '깐풍기',
      description: '바삭달콤한 깐풍기',
      category: '중식',
      expectedMinPrice: 14000,
      expectedMaxPrice: 20000,
      isDeliveryFriendly: true,
      searchKeyword: '깐풍기',
    ),
    const StarterMenu(
      id: 's106',
      name: '고추잡채',
      description: '매콤한 고추잡채',
      category: '중식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isDeliveryFriendly: true,
      searchKeyword: '고추잡채',
    ),
    const StarterMenu(
      id: 's107',
      name: '탕수만두',
      description: '바삭한 탕수만두',
      category: '중식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '탕수만두',
    ),
    const StarterMenu(
      id: 's108',
      name: '중국냉면',
      description: '새콤달콤 중국식 냉면',
      category: '중식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      searchKeyword: '중국냉면',
    ),
    const StarterMenu(
      id: 's109',
      name: '짬뽕밥',
      description: '얼큰한 짬뽕에 밥 한 공기',
      category: '중식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '짬뽕밥',
    ),
    const StarterMenu(
      id: 's110',
      name: '볶짜장',
      description: '불향 가득한 볶짜장',
      category: '중식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '볶짜장',
    ),
    // 일식
    const StarterMenu(
      id: 's111',
      name: '가라아게',
      description: '바삭한 일본식 튀김',
      category: '일식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '가라아게',
    ),
    const StarterMenu(
      id: 's112',
      name: '오니기리',
      description: '든든한 주먹밥 세트',
      category: '일식',
      expectedMinPrice: 3000,
      expectedMaxPrice: 6000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '오니기리',
    ),
    const StarterMenu(
      id: 's113',
      name: '규카츠',
      description: '두툼한 소고기 카츠',
      category: '일식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 21000,
      isSoloFriendly: true,
      searchKeyword: '규카츠',
    ),
    const StarterMenu(
      id: 's114',
      name: '나베',
      description: '따뜻한 일본식 나베',
      category: '일식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 25000,
      searchKeyword: '나베',
    ),
    const StarterMenu(
      id: 's115',
      name: '사케동',
      description: '신선한 연어 사케동',
      category: '일식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      searchKeyword: '사케동',
    ),
    const StarterMenu(
      id: 's116',
      name: '우나기동',
      description: '고소한 장어 덮밥',
      category: '일식',
      expectedMinPrice: 16000,
      expectedMaxPrice: 23000,
      isSoloFriendly: true,
      searchKeyword: '우나기동',
    ),
    const StarterMenu(
      id: 's117',
      name: '야키토리',
      description: '숯불에 구운 닭꼬치',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 14000,
      searchKeyword: '야키토리',
    ),
    const StarterMenu(
      id: 's118',
      name: '오코노미야끼',
      description: '고소한 일본식 부침개',
      category: '일식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isTakeoutFriendly: true,
      searchKeyword: '오코노미야끼',
    ),
    const StarterMenu(
      id: 's119',
      name: '다코야끼',
      description: '쫀득한 문어빵',
      category: '일식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 8000,
      isTakeoutFriendly: true,
      searchKeyword: '다코야끼',
    ),
    const StarterMenu(
      id: 's120',
      name: '챠슈동',
      description: '진한 챠슈 덮밥',
      category: '일식',
      expectedMinPrice: 11000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      searchKeyword: '챠슈동',
    ),
    // 양식
    const StarterMenu(
      id: 's121',
      name: '크림파스타',
      description: '부드러운 크림파스타',
      category: '양식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      searchKeyword: '크림파스타',
    ),
    const StarterMenu(
      id: 's122',
      name: '로제파스타',
      description: '매콤달콤 로제파스타',
      category: '양식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isSoloFriendly: true,
      searchKeyword: '로제파스타',
    ),
    const StarterMenu(
      id: 's123',
      name: '봉골레파스타',
      description: '시원한 조개 봉골레파스타',
      category: '양식',
      expectedMinPrice: 13000,
      expectedMaxPrice: 19000,
      isSoloFriendly: true,
      searchKeyword: '봉골레파스타',
    ),
    const StarterMenu(
      id: 's124',
      name: '리조또',
      description: '진한 크림 리조또',
      category: '양식',
      expectedMinPrice: 13000,
      expectedMaxPrice: 19000,
      isSoloFriendly: true,
      searchKeyword: '리조또',
    ),
    const StarterMenu(
      id: 's125',
      name: '필라프',
      description: '고소한 볶음밥 필라프',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      searchKeyword: '필라프',
    ),
    const StarterMenu(
      id: 's126',
      name: '오믈렛',
      description: '폭신한 치즈 오믈렛',
      category: '양식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      searchKeyword: '오믈렛',
    ),
    const StarterMenu(
      id: 's127',
      name: '브런치세트',
      description: '든든한 브런치 플레이트',
      category: '양식',
      expectedMinPrice: 14000,
      expectedMaxPrice: 20000,
      isSoloFriendly: true,
      searchKeyword: '브런치',
    ),
    const StarterMenu(
      id: 's128',
      name: '폭찹',
      description: '두툼한 폭찹 스테이크',
      category: '양식',
      expectedMinPrice: 16000,
      expectedMaxPrice: 24000,
      searchKeyword: '폭찹',
    ),
    const StarterMenu(
      id: 's129',
      name: '그라탕',
      description: '치즈 듬뿍 그라탕',
      category: '양식',
      expectedMinPrice: 11000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      searchKeyword: '그라탕',
    ),
    const StarterMenu(
      id: 's130',
      name: '뇨끼',
      description: '쫄깃한 감자 뇨끼',
      category: '양식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      isVeganOption: true,
      searchKeyword: '뇨끼',
    ),
    // 분식
    const StarterMenu(
      id: 's131',
      name: '순대',
      description: '쫄깃한 순대 한 접시',
      category: '분식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '순대',
    ),
    const StarterMenu(
      id: 's132',
      name: '튀김모둠',
      description: '바삭한 모둠 튀김',
      category: '분식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 9000,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '튀김',
    ),
    const StarterMenu(
      id: 's133',
      name: '어묵꼬치',
      description: '따뜻한 국물 어묵꼬치',
      category: '분식',
      expectedMinPrice: 3000,
      expectedMaxPrice: 6000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '어묵꼬치',
    ),
    const StarterMenu(
      id: 's134',
      name: '계란빵',
      description: '폭신한 계란빵',
      category: '분식',
      expectedMinPrice: 2000,
      expectedMaxPrice: 4000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '계란빵',
    ),
    const StarterMenu(
      id: 's135',
      name: '핫도그',
      description: '바삭한 감자 핫도그',
      category: '분식',
      expectedMinPrice: 3000,
      expectedMaxPrice: 5000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '핫도그',
    ),
    const StarterMenu(
      id: 's136',
      name: '쫄면',
      description: '새콤매콤 쫄면',
      category: '분식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '쫄면',
    ),
    const StarterMenu(
      id: 's137',
      name: '돈까스김밥',
      description: '든든한 돈까스김밥',
      category: '분식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 8000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '돈까스김밥',
    ),
    const StarterMenu(
      id: 's138',
      name: '새우튀김',
      description: '바삭한 새우튀김',
      category: '분식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 10000,
      isTakeoutFriendly: true,
      searchKeyword: '새우튀김',
    ),
    // 치킨
    const StarterMenu(
      id: 's139',
      name: '후라이드치킨',
      description: '바삭한 후라이드치킨',
      category: '치킨',
      expectedMinPrice: 18000,
      expectedMaxPrice: 23000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '후라이드치킨',
    ),
    const StarterMenu(
      id: 's140',
      name: '양념치킨',
      description: '달콤매콤 양념치킨',
      category: '치킨',
      expectedMinPrice: 19000,
      expectedMaxPrice: 24000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '양념치킨',
    ),
    const StarterMenu(
      id: 's141',
      name: '반반치킨',
      description: '후라이드+양념 반반',
      category: '치킨',
      expectedMinPrice: 19000,
      expectedMaxPrice: 24000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '반반치킨',
    ),
    const StarterMenu(
      id: 's142',
      name: '파닭',
      description: '아삭한 파와 치킨',
      category: '치킨',
      expectedMinPrice: 19000,
      expectedMaxPrice: 25000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '파닭',
    ),
    const StarterMenu(
      id: 's143',
      name: '순살치킨',
      description: '먹기 편한 순살치킨',
      category: '치킨',
      expectedMinPrice: 19000,
      expectedMaxPrice: 25000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '순살치킨',
    ),
    const StarterMenu(
      id: 's144',
      name: '간장치킨',
      description: '짭짤달콤 간장치킨',
      category: '치킨',
      expectedMinPrice: 19000,
      expectedMaxPrice: 24000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '간장치킨',
    ),
    // 피자
    const StarterMenu(
      id: 's145',
      name: '페퍼로니피자',
      description: '클래식 페퍼로니피자',
      category: '피자',
      expectedMinPrice: 18000,
      expectedMaxPrice: 26000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '페퍼로니피자',
    ),
    const StarterMenu(
      id: 's146',
      name: '고구마피자',
      description: '달콤한 고구마무스 피자',
      category: '피자',
      expectedMinPrice: 19000,
      expectedMaxPrice: 27000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '고구마피자',
    ),
    const StarterMenu(
      id: 's147',
      name: '콤비네이션피자',
      description: '여러 토핑 콤비네이션피자',
      category: '피자',
      expectedMinPrice: 19000,
      expectedMaxPrice: 27000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '콤비네이션피자',
    ),
    const StarterMenu(
      id: 's148',
      name: '포테이토피자',
      description: '고소한 감자 토핑 피자',
      category: '피자',
      expectedMinPrice: 19000,
      expectedMaxPrice: 27000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '포테이토피자',
    ),
    const StarterMenu(
      id: 's149',
      name: '불고기피자',
      description: '한국식 불고기 피자',
      category: '피자',
      expectedMinPrice: 19000,
      expectedMaxPrice: 27000,
      isDeliveryFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '불고기피자',
    ),
    // 햄버거
    const StarterMenu(
      id: 's150',
      name: '치즈버거',
      description: '고소한 치즈버거',
      category: '햄버거',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치즈버거',
    ),
    const StarterMenu(
      id: 's151',
      name: '베이컨버거',
      description: '짭짤한 베이컨버거',
      category: '햄버거',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '베이컨버거',
    ),
    const StarterMenu(
      id: 's152',
      name: '새우버거',
      description: '탱글한 새우패티버거',
      category: '햄버거',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '새우버거',
    ),
    const StarterMenu(
      id: 's153',
      name: '불고기버거',
      description: '한국식 불고기버거',
      category: '햄버거',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '불고기버거',
    ),
    const StarterMenu(
      id: 's154',
      name: '더블패티버거',
      description: '두 배로 든든한 버거',
      category: '햄버거',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '더블패티버거',
    ),
    // 고기
    const StarterMenu(
      id: 's155',
      name: '갈비살',
      description: '부드러운 갈비살구이',
      category: '고기',
      expectedMinPrice: 16000,
      expectedMaxPrice: 24000,
      searchKeyword: '갈비살',
    ),
    const StarterMenu(
      id: 's156',
      name: '항정살',
      description: '쫄깃한 항정살구이',
      category: '고기',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '항정살',
    ),
    const StarterMenu(
      id: 's157',
      name: '소갈비살',
      description: '진한 풍미의 소갈비살',
      category: '고기',
      expectedMinPrice: 20000,
      expectedMaxPrice: 30000,
      searchKeyword: '소갈비살',
    ),
    const StarterMenu(
      id: 's158',
      name: '오리주물럭',
      description: '매콤한 오리주물럭',
      category: '고기',
      expectedMinPrice: 16000,
      expectedMaxPrice: 23000,
      searchKeyword: '오리주물럭',
    ),
    const StarterMenu(
      id: 's159',
      name: '등갈비',
      description: '달콤짭짤 등갈비',
      category: '고기',
      expectedMinPrice: 16000,
      expectedMaxPrice: 23000,
      searchKeyword: '등갈비',
    ),
    const StarterMenu(
      id: 's160',
      name: '우삼겹',
      description: '부드러운 우삼겹구이',
      category: '고기',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '우삼겹',
    ),
    const StarterMenu(
      id: 's161',
      name: '차돌박이',
      description: '얇고 고소한 차돌박이',
      category: '고기',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '차돌박이',
    ),
    const StarterMenu(
      id: 's162',
      name: '훈제오리',
      description: '담백한 훈제오리',
      category: '고기',
      expectedMinPrice: 16000,
      expectedMaxPrice: 23000,
      searchKeyword: '훈제오리',
    ),
    // 해산물
    const StarterMenu(
      id: 's163',
      name: '전복죽',
      description: '든든한 전복죽',
      category: '해산물',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isSoloFriendly: true,
      searchKeyword: '전복죽',
    ),
    const StarterMenu(
      id: 's164',
      name: '조개찜',
      description: '시원한 조개찜',
      category: '해산물',
      expectedMinPrice: 18000,
      expectedMaxPrice: 26000,
      searchKeyword: '조개찜',
    ),
    const StarterMenu(
      id: 's165',
      name: '해물찜',
      description: '푸짐한 해물찜',
      category: '해산물',
      expectedMinPrice: 25000,
      expectedMaxPrice: 40000,
      searchKeyword: '해물찜',
    ),
    const StarterMenu(
      id: 's166',
      name: '물회',
      description: '새콤달콤 시원한 물회',
      category: '해산물',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isSoloFriendly: true,
      searchKeyword: '물회',
    ),
    const StarterMenu(
      id: 's167',
      name: '문어숙회',
      description: '쫄깃한 문어숙회',
      category: '해산물',
      expectedMinPrice: 18000,
      expectedMaxPrice: 26000,
      searchKeyword: '문어숙회',
    ),
    const StarterMenu(
      id: 's168',
      name: '랍스터롤',
      description: '고급스러운 랍스터롤',
      category: '해산물',
      expectedMinPrice: 18000,
      expectedMaxPrice: 28000,
      isSoloFriendly: true,
      searchKeyword: '랍스터롤',
    ),
    // 샐러드
    const StarterMenu(
      id: 's169',
      name: '치킨샐러드',
      description: '담백한 닭가슴살 샐러드',
      category: '샐러드',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '치킨샐러드',
    ),
    const StarterMenu(
      id: 's170',
      name: '연어샐러드',
      description: '신선한 연어 샐러드',
      category: '샐러드',
      expectedMinPrice: 11000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '연어샐러드',
    ),
    const StarterMenu(
      id: 's171',
      name: '콥샐러드',
      description: '푸짐한 콥샐러드',
      category: '샐러드',
      expectedMinPrice: 10000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '콥샐러드',
    ),
    const StarterMenu(
      id: 's172',
      name: '그릭샐러드',
      description: '상큼한 그릭샐러드',
      category: '샐러드',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '그릭샐러드',
    ),
    const StarterMenu(
      id: 's173',
      name: '두부샐러드',
      description: '건강한 두부샐러드',
      category: '샐러드',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '두부샐러드',
    ),
    // 디저트
    const StarterMenu(
      id: 's174',
      name: '마카롱',
      description: '알록달록 마카롱',
      category: '디저트',
      expectedMinPrice: 2500,
      expectedMaxPrice: 4000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '마카롱',
    ),
    const StarterMenu(
      id: 's175',
      name: '티라미수',
      description: '진한 티라미수',
      category: '디저트',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '티라미수',
    ),
    const StarterMenu(
      id: 's176',
      name: '크로플',
      description: '바삭한 크로플',
      category: '디저트',
      expectedMinPrice: 5000,
      expectedMaxPrice: 8000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '크로플',
    ),
    const StarterMenu(
      id: 's177',
      name: '와플',
      description: '달콤한 와플',
      category: '디저트',
      expectedMinPrice: 5000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '와플',
    ),
    const StarterMenu(
      id: 's178',
      name: '팬케이크',
      description: '폭신한 팬케이크',
      category: '디저트',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      searchKeyword: '팬케이크',
    ),
    const StarterMenu(
      id: 's179',
      name: '초코케이크',
      description: '진한 초콜릿 케이크',
      category: '디저트',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '초코케이크',
    ),
    const StarterMenu(
      id: 's180',
      name: '붕어빵',
      description: '고소한 팥 붕어빵',
      category: '디저트',
      expectedMinPrice: 2000,
      expectedMaxPrice: 4000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '붕어빵',
    ),
    // 카페
    const StarterMenu(
      id: 's181',
      name: '아메리카노',
      description: '깔끔한 아메리카노',
      category: '카페',
      expectedMinPrice: 2500,
      expectedMaxPrice: 4500,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '아메리카노',
    ),
    const StarterMenu(
      id: 's182',
      name: '카페라떼',
      description: '부드러운 카페라떼',
      category: '카페',
      expectedMinPrice: 3500,
      expectedMaxPrice: 5500,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '카페라떼',
    ),
    const StarterMenu(
      id: 's183',
      name: '딸기라떼',
      description: '상큼한 딸기라떼',
      category: '카페',
      expectedMinPrice: 4500,
      expectedMaxPrice: 6500,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '딸기라떼',
    ),
    const StarterMenu(
      id: 's184',
      name: '아이스티',
      description: '시원한 아이스티',
      category: '카페',
      expectedMinPrice: 3000,
      expectedMaxPrice: 5000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '아이스티',
    ),
    const StarterMenu(
      id: 's185',
      name: '스무디',
      description: '상큼한 과일 스무디',
      category: '카페',
      expectedMinPrice: 4500,
      expectedMaxPrice: 6500,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '스무디',
    ),
    // 술집
    const StarterMenu(
      id: 's186',
      name: '닭발',
      description: '매콤쫄깃 닭발',
      category: '술집',
      expectedMinPrice: 13000,
      expectedMaxPrice: 18000,
      isDeliveryFriendly: true,
      searchKeyword: '닭발',
    ),
    const StarterMenu(
      id: 's187',
      name: '오돌뼈',
      description: '쫄깃한 오돌뼈볶음',
      category: '술집',
      expectedMinPrice: 13000,
      expectedMaxPrice: 18000,
      isDeliveryFriendly: true,
      searchKeyword: '오돌뼈',
    ),
    const StarterMenu(
      id: 's188',
      name: '골뱅이무침',
      description: '새콤매콤 골뱅이무침',
      category: '술집',
      expectedMinPrice: 14000,
      expectedMaxPrice: 20000,
      searchKeyword: '골뱅이무침',
    ),
    const StarterMenu(
      id: 's189',
      name: '해물파전',
      description: '바삭한 해물파전',
      category: '술집',
      expectedMinPrice: 13000,
      expectedMaxPrice: 18000,
      isTakeoutFriendly: true,
      searchKeyword: '해물파전',
    ),
    const StarterMenu(
      id: 's190',
      name: '감바스',
      description: '마늘 향 가득 감바스',
      category: '술집',
      expectedMinPrice: 14000,
      expectedMaxPrice: 20000,
      searchKeyword: '감바스',
    ),
    const StarterMenu(
      id: 's191',
      name: '나초',
      description: '치즈 듬뿍 나초',
      category: '술집',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '나초',
    ),
    const StarterMenu(
      id: 's192',
      name: '치즈플래터',
      description: '다양한 치즈 플래터',
      category: '술집',
      expectedMinPrice: 18000,
      expectedMaxPrice: 26000,
      searchKeyword: '치즈플래터',
    ),
    const StarterMenu(
      id: 's193',
      name: '먹태',
      description: '고소한 먹태',
      category: '술집',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isTakeoutFriendly: true,
      searchKeyword: '먹태',
    ),
    const StarterMenu(
      id: 's194',
      name: '노가리',
      description: '짭짤한 노가리',
      category: '술집',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isTakeoutFriendly: true,
      searchKeyword: '노가리',
    ),
    const StarterMenu(
      id: 's195',
      name: '모둠꼬치',
      description: '숯불 향 모둠꼬치',
      category: '술집',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      searchKeyword: '모둠꼬치',
    ),
    const StarterMenu(
      id: 's196',
      name: '닭꼬치',
      description: '달콤짭짤 닭꼬치',
      category: '술집',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isTakeoutFriendly: true,
      searchKeyword: '닭꼬치',
    ),
    const StarterMenu(
      id: 's197',
      name: '조개탕',
      description: '시원한 조개탕',
      category: '술집',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      searchKeyword: '조개탕',
    ),
    // 야식
    const StarterMenu(
      id: 's198',
      name: '족발보쌈세트',
      description: '푸짐한 족발보쌈 세트',
      category: '야식',
      expectedMinPrice: 28000,
      expectedMaxPrice: 38000,
      isDeliveryFriendly: true,
      searchKeyword: '족발보쌈세트',
    ),
    const StarterMenu(
      id: 's199',
      name: '불닭발',
      description: '화끈하게 매운 불닭발',
      category: '야식',
      expectedMinPrice: 13000,
      expectedMaxPrice: 19000,
      isDeliveryFriendly: true,
      searchKeyword: '불닭발',
    ),
    const StarterMenu(
      id: 's200',
      name: '치즈스틱',
      description: '쭉 늘어나는 치즈스틱',
      category: '야식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 8000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치즈스틱',
    ),
    const StarterMenu(
      id: 's201',
      name: '닭똥집볶음',
      description: '쫄깃 매콤한 닭똥집볶음',
      category: '야식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 17000,
      isDeliveryFriendly: true,
      searchKeyword: '닭똥집볶음',
    ),
    const StarterMenu(
      id: 's202',
      name: '콘치즈',
      description: '달콤고소한 콘치즈',
      category: '야식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '콘치즈',
    ),
    const StarterMenu(
      id: 's203',
      name: '소시지야채볶음',
      description: '든든한 소시지야채볶음',
      category: '야식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isDeliveryFriendly: true,
      searchKeyword: '소시지야채볶음',
    ),
    // 기타
    const StarterMenu(
      id: 's204',
      name: '브리또',
      description: '든든한 멕시칸 브리또',
      category: '기타',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '브리또',
    ),
    const StarterMenu(
      id: 's205',
      name: '케밥',
      description: '든든한 터키식 케밥',
      category: '기타',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '케밥',
    ),
    const StarterMenu(
      id: 's206',
      name: '월남쌈',
      description: '건강한 월남쌈',
      category: '기타',
      expectedMinPrice: 15000,
      expectedMaxPrice: 22000,
      isVeganOption: true,
      searchKeyword: '월남쌈',
    ),
  ];

  @override
  Future<List<MenuItem>> fetchApprovedMenus() async {
    await Future.delayed(const Duration(milliseconds: 150));
    for (final m in _menus) {
      m.restaurant = _rMap[m.restaurantId];
    }
    return List.of(_menus);
  }

  @override
  Future<List<StarterMenu>> fetchStarterMenus() async {
    await Future.delayed(const Duration(milliseconds: 150));
    return List.of(_starters);
  }

  @override
  Future<List<MenuItem>> fetchOwnerMenus(String ownerId) async => [];

  @override
  Future<void> submitMenu(MenuItem menu) async {
    // mock 모드에서는 자동 승인 후 목록에 추가 (개발 편의)
    if (AppConfig.autoApproveMenuInDev) {
      _menus.add(menu);
    }
  }

  @override
  Future<void> approveMenu(String menuId) async {}

  @override
  Future<void> rejectMenu(String menuId, String note) async {}
}
