import '../config/app_config.dart';
import '../models/menu_item.dart';
import '../models/restaurant.dart';
import '../models/starter_menu.dart';
import 'menu_repository.dart';

/// Supabase 미연결 시 사용하는 로컬 mock 데이터.
/// 등록 메뉴(가게 포함) + 스타터 메뉴를 제공합니다.
class MockDataRepository implements MenuRepository {
  static final List<Restaurant> _restaurants = [
    Restaurant(
      id: 'r1',
      name: '주먹식당',
      address: '서울 강남구 강남대로 396',
      phone: '02-1234-5678',
      lat: 37.4985,
      lng: 127.0272,
      category: '한식',
      source: 'admin_seed',
      isTakeoutAvailable: true,
    ),
    Restaurant(
      id: 'r2',
      name: '혼밥왕국',
      address: '서울 강남구 테헤란로 151',
      phone: '02-2345-6789',
      lat: 37.4992,
      lng: 127.0284,
      category: '한식',
      source: 'admin_seed',
      isDeliveryAvailable: true,
    ),
    Restaurant(
      id: 'r3',
      name: '면식당',
      address: '서울 강남구 역삼로 160',
      phone: '02-3456-7890',
      lat: 37.4968,
      lng: 127.0299,
      category: '일식',
      source: 'admin_seed',
      isTakeoutAvailable: true,
      isDeliveryAvailable: true,
    ),
  ];

  static final Map<String, Restaurant> _rMap = {
    for (final r in _restaurants) r.id: r,
  };

  static final List<MenuItem> _menus = [
    MenuItem(
      id: 'm1',
      restaurantId: 'r1',
      name: '김치제육덮밥',
      description: '매콤한 제육볶음과 신선한 김치가 어우러진 한 그릇 밥',
      price: 9500,
      category: '한식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      spicyLevel: 3,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm2',
      restaurantId: 'r1',
      name: '된장찌개 정식',
      description: '깊은 맛의 된장찌개와 밥, 반찬 3가지',
      price: 8000,
      category: '한식',
      isSoloFriendly: true,
      spicyLevel: 1,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm3',
      restaurantId: 'r1',
      name: '비빔밥 (채식)',
      description: '고추장 대신 간장 양념, 비건 가능',
      price: 8500,
      category: '한식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      isVeganOption: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm4',
      restaurantId: 'r2',
      name: '순대국밥',
      description: '진한 육수의 순대국밥, 1인 세트',
      price: 7500,
      category: '한식',
      isDeliveryAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm5',
      restaurantId: 'r2',
      name: '참치마요덮밥',
      description: '참치와 마요네즈의 조화',
      price: 7000,
      category: '한식',
      isDeliveryAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm6',
      restaurantId: 'r3',
      name: '돈카츠',
      description: '바삭한 등심 돈카츠',
      price: 11000,
      category: '일식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      source: 'admin_seed',
    ),
    MenuItem(
      id: 'm7',
      restaurantId: 'r3',
      name: '냉모밀',
      description: '시원한 메밀 소바',
      price: 9000,
      category: '일식',
      isTakeoutAvailable: true,
      isSoloFriendly: true,
      isVeganOption: true,
      source: 'admin_seed',
    ),
  ];

  static final List<StarterMenu> _starters = [
    const StarterMenu(
      id: 's1',
      name: '김치제육덮밥',
      description: '매콤한 제육볶음과 김치',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '김치제육덮밥',
    ),
    const StarterMenu(
      id: 's2',
      name: '된장찌개 정식',
      description: '구수한 된장찌개 정식',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '된장찌개',
    ),
    const StarterMenu(
      id: 's3',
      name: '비빔밥',
      description: '나물과 고추장의 조화',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '비빔밥',
    ),
    const StarterMenu(
      id: 's4',
      name: '순두부찌개',
      description: '얼큰한 순두부찌개',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '순두부찌개',
    ),
    const StarterMenu(
      id: 's5',
      name: '국밥',
      description: '뜨끈한 국밥 한 그릇',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '국밥',
    ),
    const StarterMenu(
      id: 's6',
      name: '짜장면',
      description: '진한 춘장 소스',
      category: '중식',
      expectedMinPrice: 6000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '짜장면',
    ),
    const StarterMenu(
      id: 's7',
      name: '마라탕',
      description: '얼얼한 마라 향신료',
      category: '중식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '마라탕',
    ),
    const StarterMenu(
      id: 's8',
      name: '짬뽕',
      description: '얼큰한 해물 국물',
      category: '중식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '짬뽕',
    ),
    const StarterMenu(
      id: 's9',
      name: '초밥',
      description: '신선한 한 입 초밥',
      category: '일식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 20000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '초밥',
    ),
    const StarterMenu(
      id: 's10',
      name: '돈카츠',
      description: '바삭한 돈카츠',
      category: '일식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '돈카츠',
    ),
    const StarterMenu(
      id: 's11',
      name: '냉모밀',
      description: '시원한 소바',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '냉모밀',
    ),
    const StarterMenu(
      id: 's12',
      name: '우동',
      description: '뜨끈한 우동',
      category: '일식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '우동',
    ),
    const StarterMenu(
      id: 's13',
      name: '알리오올리오',
      description: '마늘 올리브오일 파스타',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '알리오올리오',
    ),
    const StarterMenu(
      id: 's14',
      name: '토마토파스타',
      description: '신선한 토마토 소스',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '토마토파스타',
    ),
    const StarterMenu(
      id: 's15',
      name: '샐러드볼',
      description: '채소와 단백질의 건강 한 그릇',
      category: '양식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '샐러드볼',
    ),
    const StarterMenu(
      id: 's16',
      name: '떡볶이',
      description: '매콤한 떡볶이',
      category: '분식',
      expectedMinPrice: 4000,
      expectedMaxPrice: 8000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '떡볶이',
    ),
    const StarterMenu(
      id: 's17',
      name: '김밥',
      description: '한국식 롤',
      category: '분식',
      expectedMinPrice: 3000,
      expectedMaxPrice: 6000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '김밥',
    ),
    const StarterMenu(
      id: 's18',
      name: '라볶이',
      description: '라면+떡볶이 조합',
      category: '분식',
      expectedMinPrice: 5000,
      expectedMaxPrice: 9000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '라볶이',
    ),
    const StarterMenu(
      id: 's19',
      name: '햄버거세트',
      description: '버거+감자튀김 세트',
      category: '패스트푸드',
      expectedMinPrice: 7000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '햄버거',
    ),
    const StarterMenu(
      id: 's20',
      name: '치킨버거',
      description: '바삭한 치킨 버거',
      category: '패스트푸드',
      expectedMinPrice: 6000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치킨버거',
    ),
    const StarterMenu(
      id: 's21',
      name: '쌀국수',
      description: '베트남식 쌀국수',
      category: '양식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '쌀국수 포',
    ),
    const StarterMenu(
      id: 's22',
      name: '아보카도 토스트',
      description: '건강 브런치',
      category: '카페/디저트',
      expectedMinPrice: 9000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isVeganOption: true,
      searchKeyword: '아보카도토스트',
    ),
    // s23~s50 추가
    const StarterMenu(
      id: 's23',
      name: '김치찌개',
      description: '진한 김치 국물에 돼지고기와 두부',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '김치찌개',
    ),
    const StarterMenu(
      id: 's24',
      name: '순댓국',
      description: '구수한 순대국 한 그릇',
      category: '한식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 10000,
      isSoloFriendly: true,
      searchKeyword: '순댓국',
    ),
    const StarterMenu(
      id: 's25',
      name: '설렁탕',
      description: '오래 끓인 맑은 사골 육수',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      searchKeyword: '설렁탕',
    ),
    const StarterMenu(
      id: 's26',
      name: '갈비탕',
      description: '진한 소갈비 국물',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      searchKeyword: '갈비탕',
    ),
    const StarterMenu(
      id: 's27',
      name: '부대찌개',
      description: '햄·소시지·라면이 들어간 얼큰 찌개',
      category: '한식',
      expectedMinPrice: 9000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '부대찌개',
    ),
    const StarterMenu(
      id: 's28',
      name: '제육볶음',
      description: '매콤달콤한 돼지고기 볶음',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '제육볶음',
    ),
    const StarterMenu(
      id: 's29',
      name: '불고기',
      description: '달콤한 간장 양념 소불고기',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '불고기',
    ),
    const StarterMenu(
      id: 's30',
      name: '삼겹살',
      description: '두툼한 삼겹살 구이',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 20000,
      searchKeyword: '삼겹살',
    ),
    const StarterMenu(
      id: 's31',
      name: '닭갈비',
      description: '매콤한 춘천식 닭갈비',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '닭갈비',
    ),
    const StarterMenu(
      id: 's32',
      name: '찜닭',
      description: '달콤짭짤한 안동식 찜닭',
      category: '한식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 18000,
      isDeliveryFriendly: true,
      searchKeyword: '찜닭',
    ),
    const StarterMenu(
      id: 's33',
      name: '닭강정',
      description: '바삭하고 달콤한 닭강정',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 14000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '닭강정',
    ),
    const StarterMenu(
      id: 's34',
      name: '치킨',
      description: '바삭한 프라이드 치킨',
      category: '패스트푸드',
      expectedMinPrice: 10000,
      expectedMaxPrice: 20000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '치킨',
    ),
    const StarterMenu(
      id: 's35',
      name: '족발',
      description: '쫄깃한 족발 보쌈 세트',
      category: '한식',
      expectedMinPrice: 15000,
      expectedMaxPrice: 25000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '족발',
    ),
    const StarterMenu(
      id: 's36',
      name: '보쌈',
      description: '수육과 김치를 함께 즐기는 보쌈',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 22000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '보쌈',
    ),
    const StarterMenu(
      id: 's37',
      name: '곱창볶음',
      description: '매콤하게 볶은 소곱창',
      category: '한식',
      expectedMinPrice: 12000,
      expectedMaxPrice: 18000,
      isSoloFriendly: true,
      searchKeyword: '곱창',
    ),
    const StarterMenu(
      id: 's38',
      name: '감자탕',
      description: '칼칼한 돼지 등뼈 감자탕',
      category: '한식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '감자탕',
    ),
    const StarterMenu(
      id: 's39',
      name: '라면',
      description: '얼큰하고 뜨끈한 라면 한 그릇',
      category: '분식',
      expectedMinPrice: 4000,
      expectedMaxPrice: 7000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      searchKeyword: '라면',
    ),
    const StarterMenu(
      id: 's40',
      name: '순대볶음',
      description: '야채와 함께 볶은 매콤한 순대',
      category: '분식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '순대',
    ),
    const StarterMenu(
      id: 's41',
      name: '오므라이스',
      description: '계란 오믈렛에 케첩 볶음밥',
      category: '양식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '오므라이스',
    ),
    const StarterMenu(
      id: 's42',
      name: '라멘',
      description: '진한 국물의 일본식 라멘',
      category: '일식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 16000,
      isSoloFriendly: true,
      searchKeyword: '라멘',
    ),
    const StarterMenu(
      id: 's43',
      name: '규동',
      description: '달콤한 소고기 덮밥',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '규동',
    ),
    const StarterMenu(
      id: 's44',
      name: '탕수육',
      description: '바삭한 탕수육과 새콤달콤한 소스',
      category: '중식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 18000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '탕수육',
    ),
    const StarterMenu(
      id: 's45',
      name: '볶음밥',
      description: '고소한 계란 볶음밥',
      category: '중식',
      expectedMinPrice: 7000,
      expectedMaxPrice: 11000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '볶음밥',
    ),
    const StarterMenu(
      id: 's46',
      name: '피자',
      description: '쫄깃한 도우의 화덕 피자',
      category: '패스트푸드',
      expectedMinPrice: 10000,
      expectedMaxPrice: 20000,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '피자',
    ),
    const StarterMenu(
      id: 's47',
      name: '샌드위치',
      description: '신선한 재료의 수제 샌드위치',
      category: '카페/디저트',
      expectedMinPrice: 6000,
      expectedMaxPrice: 12000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '샌드위치',
    ),
    const StarterMenu(
      id: 's48',
      name: '스테이크',
      description: '부드러운 등심 스테이크',
      category: '양식',
      expectedMinPrice: 18000,
      expectedMaxPrice: 35000,
      isSoloFriendly: true,
      searchKeyword: '스테이크',
    ),
    const StarterMenu(
      id: 's49',
      name: '팟타이',
      description: '태국식 볶음 쌀국수',
      category: '양식',
      expectedMinPrice: 10000,
      expectedMaxPrice: 15000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      searchKeyword: '팟타이',
    ),
    const StarterMenu(
      id: 's50',
      name: '카레라이스',
      description: '진한 일본식 카레와 밥',
      category: '일식',
      expectedMinPrice: 8000,
      expectedMaxPrice: 13000,
      isSoloFriendly: true,
      isTakeoutFriendly: true,
      isDeliveryFriendly: true,
      isVeganOption: true,
      searchKeyword: '카레',
    ),
  ];

  @override
  Future<List<MenuItem>> fetchApprovedMenus() async {
    await Future.delayed(const Duration(milliseconds: 150));
    for (final m in _menus) {
      m.restaurant = _rMap[m.restaurantId];
    }
    return List.of(_menus);
  }

  @override
  Future<List<StarterMenu>> fetchStarterMenus() async {
    await Future.delayed(const Duration(milliseconds: 150));
    return List.of(_starters);
  }

  @override
  Future<List<MenuItem>> fetchOwnerMenus(String ownerId) async => [];

  @override
  Future<void> submitMenu(MenuItem menu) async {
    // mock 모드에서는 자동 승인 후 목록에 추가 (개발 편의)
    if (AppConfig.autoApproveMenuInDev) {
      _menus.add(menu);
    }
  }

  @override
  Future<void> approveMenu(String menuId) async {}

  @override
  Future<void> rejectMenu(String menuId, String note) async {}
}
